# Generated by Django 4.2.23 on 2026-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='中文名'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='英文名'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_correct_count',
            field=models.IntegerField(default=0, verbose_name='总正确次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_practice_count',
            field=models.IntegerField(default=0, verbose_name='总练习次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='总得分'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hsk_level',
            field=models.IntegerField(default=1, verbose_name='HSK水平'),
        ),
    ]
