# Generated by Django 4.2.23 on 2026-01-07 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_avatar_user_chinese_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='徽章代码')),
                ('name', models.CharField(max_length=100, verbose_name='徽章名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('icon_url', models.URLField(blank=True, max_length=500, verbose_name='图标URL')),
                ('requirement', models.JSONField(verbose_name='获取条件')),
                ('points', models.IntegerField(default=0, verbose_name='奖励积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成就徽章',
                'verbose_name_plural': '成就徽章',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='持续时间(秒)')),
                ('activity_type', models.CharField(choices=[('practice', '练习'), ('exam', '考试'), ('culture', '文化学习'), ('university', '院校浏览')], max_length=50, verbose_name='活动类型')),
                ('activity_id', models.IntegerField(null=True, verbose_name='活动ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习会话',
                'verbose_name_plural': '学习会话',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('custom', '自定义')], max_length=20, verbose_name='报告类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('summary', models.JSONField(verbose_name='统计摘要')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习报告',
                'verbose_name_plural': '学习报告',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hsk_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='HSK等级最小为1'), django.core.validators.MaxValueValidator(6, message='HSK等级最大为6')], verbose_name='目标HSK等级')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('daily_practice_count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='每日练习目标最小为1'), django.core.validators.MaxValueValidator(500, message='每日练习目标最大为500')], verbose_name='每日练习目标')),
                ('current_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='进度不能为负数'), django.core.validators.MaxValueValidator(100, message='进度不能大于100')], verbose_name='当前进度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习目标',
                'verbose_name_plural': '学习目标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.achievementbadge', verbose_name='徽章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='StudyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('practice_count', models.IntegerField(default=0, verbose_name='练习次数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习统计',
                'verbose_name_plural': '学习统计',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
