# Generated by Django 4.2.23 on 2026-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['ranking'], 'verbose_name': '大学', 'verbose_name_plural': '大学'},
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='校园图片URL'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='university',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='university',
            name='features',
            field=models.TextField(blank=True, verbose_name='特色'),
        ),
        migrations.AddField(
            model_name='university',
            name='history',
            field=models.TextField(blank=True, verbose_name='历史沿革'),
        ),
        migrations.AddField(
            model_name='university',
            name='international_students',
            field=models.IntegerField(default=0, verbose_name='国际学生数量'),
        ),
        migrations.AddField(
            model_name='university',
            name='language_requirements',
            field=models.TextField(blank=True, verbose_name='语言要求'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='校徽URL'),
        ),
        migrations.AddField(
            model_name='university',
            name='min_hsk_level',
            field=models.IntegerField(default=1, verbose_name='最低HSK要求'),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='university',
            name='popular_majors',
            field=models.JSONField(blank=True, null=True, verbose_name='热门专业'),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_national',
            field=models.IntegerField(blank=True, null=True, verbose_name='国内排名'),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_world',
            field=models.IntegerField(blank=True, null=True, verbose_name='世界排名'),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship',
            field=models.TextField(blank=True, verbose_name='奖学金'),
        ),
        migrations.AddField(
            model_name='university',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='university',
            name='total_students',
            field=models.IntegerField(default=0, verbose_name='学生总数'),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='学费'),
        ),
        migrations.AddField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='官方网站'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='university',
            name='majors',
            field=models.JSONField(blank=True, null=True, verbose_name='专业列表'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='大学名称'),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地区'),
        ),
    ]
