# Generated by Django 4.2.23 on 2026-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_university_options_university_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='advantages',
            field=models.JSONField(blank=True, null=True, verbose_name='优势特点(中英对照)'),
        ),
        migrations.AddField(
            model_name='university',
            name='campus_life',
            field=models.JSONField(blank=True, null=True, verbose_name='校园生活(中英对照)'),
        ),
        migrations.AddField(
            model_name='university',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文描述'),
        ),
        migrations.AddField(
            model_name='university',
            name='features_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文特色'),
        ),
        migrations.AddField(
            model_name='university',
            name='history_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文历史沿革'),
        ),
    ]
