# Generated by Django 4.2.23 on 2026-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_advantages_university_campus_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='establish_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='建校时间'),
        ),
    ]
