# Generated by Django 4.2.23 on 2026-01-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_university_establish_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='establish_year',
        ),
    ]
