# Generated by Django 4.2.23 on 2026-01-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culture', '0003_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name': '文化内容', 'verbose_name_plural': '文化内容'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AddField(
            model_name='content',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='音频链接'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('article', '文章'), ('video', '视频'), ('image', '图片'), ('audio', '音频'), ('interactive', '互动')], default='article', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='content',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '简单'), (2, '较易'), (3, '中等'), (4, '较难'), (5, '困难')], default=3, verbose_name='难度系数'),
        ),
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='时长(分钟)'),
        ),
        migrations.AddField(
            model_name='content',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='视频链接'),
        ),
        migrations.AddField(
            model_name='content',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='观看次数'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.content', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'content')},
        ),
        migrations.CreateModel(
            name='InteractiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('quiz', '测验'), ('matching', '匹配题'), ('fill_blank', '填空题'), ('multiple_choice', '选择题'), ('true_false', '判断题')], max_length=20, verbose_name='练习类型')),
                ('question', models.TextField(verbose_name='问题')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选项')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('points', models.IntegerField(default=10, verbose_name='积分')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='culture.content', verbose_name='关联内容')),
            ],
            options={
                'verbose_name': '互动练习',
                'verbose_name_plural': '互动练习',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('time_taken', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.interactiveexercise', verbose_name='练习')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习尝试',
                'verbose_name_plural': '练习尝试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('time_spent', models.IntegerField(default=0, verbose_name='花费时间(秒)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.content', verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户进度',
                'verbose_name_plural': '用户进度',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
