# Generated by Django 4.2.23 on 2026-01-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_alter_content_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文内容'),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraphs',
            field=models.JSONField(blank=True, null=True, verbose_name='段落内容(中英对照)'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='英文标题'),
        ),
    ]
