# Generated by Django 4.2.23 on 2026-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_category_description_en_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简短描述'),
        ),
        migrations.AddField(
            model_name='content',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文描述'),
        ),
        migrations.AddField(
            model_name='content',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='用于存储菜系特点、名菜、文化内涵等结构化信息', null=True, verbose_name='结构化数据'),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='英文副标题'),
        ),
    ]
