# Generated by Django 4.2.23 on 2026-01-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0007_content_description_content_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveexercise',
            name='content',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExerciseAttempt',
        ),
        migrations.DeleteModel(
            name='InteractiveExercise',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
