# Generated by Django 4.2.23 on 2025-06-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
        ('question', 'add_updated_at_field'),
    ]

    operations = [
    ]
