# Generated by Django 4.2.23 on 2025-06-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0004_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerrecord',
            options={'verbose_name': '答题记录', 'verbose_name_plural': '答题记录'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterModelOptions(
            name='wrongbook',
            options={'verbose_name': '错题本', 'verbose_name_plural': '错题本'},
        ),
        # 注释掉尝试删除不存在列的操作
        # migrations.RemoveField(
        #    model_name='answerrecord',
        #    name='answered_at',
        # ),
        # migrations.RemoveField(
        #    model_name='question',
        #    name='audio_url',
        # ),
        # migrations.RemoveField(
        #    model_name='question',
        #    name='explanation',
        # ),
        # migrations.RemoveField(
        #    model_name='question',
        #    name='image_url',
        # ),
        migrations.AddField(
            model_name='answerrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrongbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='is_correct',
            field=models.BooleanField(verbose_name='是否正确'),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='user_answer',
            field=models.TextField(verbose_name='用户答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=50, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='wrongbook',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='wrongbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='wrongbook',
            unique_together={('user', 'question')},
        ),
        # 注释掉尝试删除不存在列的操作
        # migrations.RemoveField(
        #    model_name='wrongbook',
        #    name='added_at',
        # ),
    ]
