# Generated by Django 4.2.23 on 2025-06-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0005_alter_answerrecord_options_alter_question_options_and_more'),
    ]

    operations = [
        # Comment out all operations that try to remove fields that don't exist
        # migrations.RemoveField(
        #     model_name='answerrecord',
        #     name='answered_at',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='audio_url',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='explanation',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='image_url',
        # ),
        # migrations.RemoveField(
        #     model_name='wrongbook',
        #     name='added_at',
        # ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(default='[]', verbose_name='选项'),
        ),
    ]
