# Generated by Django 4.2.23 on 2026-01-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_answerrecord_answered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vocabulary', '词汇'), ('reading', '阅读'), ('listening', '听力'), ('writing', '写作'), ('grammar', '语法'), ('comprehensive', '综合')], max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='套卷标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('level', models.IntegerField(verbose_name='难度等级')),
                ('time_limit', models.IntegerField(default=120, verbose_name='时间限制(分钟)')),
                ('question_count', models.IntegerField(default=0, verbose_name='题目数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '套卷',
                'verbose_name_plural': '套卷',
                'ordering': ['-created_at'],
            },
        ),
        # migrations.RemoveField(
        #     model_name='answerrecord',
        #     name='answered_at',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='audio_url',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='image_url',
        # ),
        # migrations.RemoveField(
        #     model_name='wrongbook',
        #     name='added_at',
        # ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '简单'), (2, '较易'), (3, '中等'), (4, '较难'), (5, '困难')], default=3, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, default='', verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.questioncategory', verbose_name='题目分类'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.questionset', verbose_name='所属套卷'),
        ),
    ]
