# Generated by Django 4.2.23 on 2026-01-07 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0007_questioncategory_questionset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='得分')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=20, verbose_name='状态')),
                ('answers', models.JSONField(default=dict, verbose_name='答案JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionset', verbose_name='套卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('hsk_level', models.IntegerField(verbose_name='HSK等级')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题目数')),
                ('imported_questions', models.IntegerField(default=0, verbose_name='已导入题目数')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试卷导入',
                'verbose_name_plural': '试卷导入',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='answerrecord',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='wrongbook',
            name='added_at',
        ),
        migrations.CreateModel(
            name='ExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(verbose_name='总题目数')),
                ('correct_count', models.IntegerField(verbose_name='正确数量')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='正确率')),
                ('time_spent', models.IntegerField(verbose_name='用时(秒)')),
                ('category_performance', models.JSONField(default=dict, verbose_name='分类表现')),
                ('weak_points', models.JSONField(default=list, verbose_name='薄弱知识点')),
                ('suggestions', models.TextField(blank=True, verbose_name='学习建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.examattempt', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '考试报告',
                'verbose_name_plural': '考试报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.examattempt', verbose_name='考试记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试评论',
                'verbose_name_plural': '考试评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='question.question', verbose_name='关联题目')),
                ('question_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='question.questionset', verbose_name='关联套卷')),
            ],
            options={
                'verbose_name': '音频文件',
                'verbose_name_plural': '音频文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分数')),
                ('time_spent', models.IntegerField(verbose_name='用时(秒)')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.examattempt', verbose_name='考试记录')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionset', verbose_name='套卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试排行榜',
                'verbose_name_plural': '考试排行榜',
                'ordering': ['rank'],
                'unique_together': {('question_set', 'user')},
            },
        ),
    ]
