# Generated by Django 4.2.23 on 2026-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_add_missing_question_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='音频时长(秒)'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/', verbose_name='音频文件'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='音频URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('fill', '填空题'), ('listening', '听力题'), ('reading', '阅读题')], max_length=50, verbose_name='题目类型'),
        ),
    ]
