# Generated by Django 4.2.23 on 2026-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_audio_duration_question_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='exam_type',
            field=models.CharField(choices=[('real', '真题'), ('mock', '模拟题'), ('sample', '样卷'), ('practice', '练习题')], default='practice', max_length=20, verbose_name='试卷类型'),
        ),
    ]
