# Generated by Django 4.2.23 on 2026-01-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_questionset_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='question',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='question_set',
        ),
        migrations.DeleteModel(
            name='PaperImport',
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['order', 'id'], 'verbose_name': '题目分类', 'verbose_name_plural': '题目分类'},
        ),
        migrations.AddField(
            model_name='question',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/', verbose_name='题目图片文件'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_pairs',
            field=models.JSONField(blank=True, null=True, verbose_name='匹配对信息'),
        ),
        migrations.AddField(
            model_name='question',
            name='ordering_items',
            field=models.JSONField(blank=True, null=True, verbose_name='排序项列表'),
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, null=True, verbose_name='文章/对话内容'),
        ),
        migrations.AddField(
            model_name='question',
            name='passage_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文章标题'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, verbose_name='分值'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_questions',
            field=models.JSONField(blank=True, null=True, verbose_name='子题目列表'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='答题时限(秒)'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='颜色标识'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='level_range',
            field=models.JSONField(blank=True, null=True, verbose_name='适用等级范围'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='question.questioncategory', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='答案解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(verbose_name='HSK等级 (1-6)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, default='', verbose_name='选项(JSON格式)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('fill', '填空题'), ('listening', '听力题'), ('dialogue', '对话理解'), ('reading', '阅读理解'), ('passage_reading', '长文阅读'), ('cloze', '完形填空'), ('image_choice', '看图选择'), ('image_description', '看图写作'), ('matching', '连线/匹配题'), ('ordering', '排序题'), ('character_writing', '汉字书写'), ('essay', '作文')], max_length=50, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(choices=[('listening_dialogue', '听力-对话理解'), ('listening_passage', '听力-短文理解'), ('listening_choice', '听力-听后选择'), ('reading_vocabulary', '阅读-词汇理解'), ('reading_grammar', '阅读-语法运用'), ('reading_passage', '阅读-文章理解'), ('reading_cloze', '阅读-完形填空'), ('writing_character', '写作-汉字书写'), ('writing_sentence', '写作-句子造句'), ('writing_essay', '写作-作文'), ('writing_practical', '写作-应用文'), ('comprehensive_matching', '综合-词语搭配'), ('comprehensive_ordering', '综合-句子排序'), ('comprehensive_image', '综合-看图说话'), ('vocabulary', '词汇专项'), ('grammar', '语法专项'), ('culture', '文化常识')], max_length=50, verbose_name='分类名称'),
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
