# Generated by Django 4.2.23 on 2026-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_remove_audiofile_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='音频URL或路径'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL或路径'),
        ),
    ]
