# Generated by Django 4.2.23 on 2026-01-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_question_audio_url_alter_question_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='音频分组标识'),
        ),
    ]
