# Generated by Django 4.2.23 on 2026-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_question_audio_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='材料标题')),
                ('level', models.IntegerField(choices=[(1, 'HSK1'), (2, 'HSK2'), (3, 'HSK3'), (4, 'HSK4'), (5, 'HSK5'), (6, 'HSK6')], verbose_name='HSK等级')),
                ('section_type', models.CharField(choices=[('listening', '听力'), ('reading', '阅读'), ('writing', '书写')], max_length=20, verbose_name='部分类型')),
                ('part_number', models.IntegerField(verbose_name='第几部分')),
                ('content', models.TextField(blank=True, verbose_name='文字内容')),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='音频URL')),
                ('audio_duration', models.IntegerField(default=0, verbose_name='音频时长（秒）')),
                ('material_group', models.CharField(max_length=100, unique=True, verbose_name='材料组标识')),
                ('play_times', models.IntegerField(default=2, verbose_name='播放次数')),
                ('question_range_start', models.IntegerField(verbose_name='题号起始')),
                ('question_range_end', models.IntegerField(verbose_name='题号结束')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试材料',
                'verbose_name_plural': '考试材料',
                'ordering': ['level', 'section_type', 'part_number', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='material_group',
            field=models.CharField(blank=True, help_text='与Material模型的material_group关联', max_length=100, null=True, verbose_name='材料组标识'),
        ),
        migrations.AddField(
            model_name='question',
            name='part_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='第几部分'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='题号'),
        ),
        migrations.AddField(
            model_name='question',
            name='section_type',
            field=models.CharField(blank=True, choices=[('listening', '听力'), ('reading', '阅读'), ('writing', '书写')], max_length=20, null=True, verbose_name='部分类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('listening_image_judge', '听力-图片判断（✓/✗）'), ('listening_image_choice', '听力-图片选择'), ('listening_dialogue_image', '听力-对话配图'), ('listening_text_choice', '听力-文字选择'), ('reading_image_word_match', '阅读-图片词语匹配'), ('reading_sentence_image_match', '阅读-句子图片匹配'), ('reading_dialogue_match', '阅读-对话匹配'), ('reading_fill_blank', '阅读-选词填空'), ('reading_judge', '阅读-判断对错'), ('listening_long_dialogue', '听力-长对话理解'), ('listening_comprehension', '听力-听力理解'), ('reading_comprehension', '阅读-阅读理解'), ('reading_cloze', '阅读-完形填空'), ('reading_sentence_match', '阅读-句子匹配'), ('writing_sentence_order', '书写-组句'), ('writing_fill_hanzi', '书写-汉字填空'), ('writing_composition', '书写-作文'), ('writing_summary', '书写-文章缩写'), ('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('listening', '听力题'), ('reading', '阅读题')], max_length=50, verbose_name='题目类型'),
        ),
    ]
