# Generated by Django 4.2.23 on 2026-01-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_material_question_material_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('listening_image_judge', '听力-图片判断（✓/✗）'), ('listening_image_choice', '听力-图片选择'), ('listening_dialogue_image', '听力-对话配图'), ('listening_text_choice', '听力-文字选择'), ('reading_image_word_match', '阅读-图片词语匹配'), ('reading_sentence_image_match', '阅读-句子图片匹配'), ('reading_dialogue_match', '阅读-对话匹配'), ('reading_fill_blank', '阅读-选词填空'), ('reading_judge', '阅读-判断对错'), ('listening_long_dialogue', '听力-长对话理解'), ('listening_comprehension', '听力-听力理解'), ('reading_comprehension', '阅读-阅读理解'), ('reading_cloze', '阅读-完形填空'), ('reading_sentence_match', '阅读-句子匹配'), ('writing_sentence_order', '书写-组句'), ('writing_fill_hanzi', '书写-汉字填空'), ('writing_composition', '书写-作文'), ('writing_summary', '书写-文章缩写'), ('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('fill', '填空题'), ('listening', '听力题'), ('reading', '阅读题'), ('writing', '书写题')], max_length=50, verbose_name='题目类型'),
        ),
    ]
