# Generated by Django 4.2.23 on 2026-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_add_additional_question_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('listening', '听力题'), ('reading', '阅读题'), ('writing', '书写题'), ('fill', '填空题'), ('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题')], max_length=50, verbose_name='题目类型'),
        ),
    ]
