# Generated by Django 4.2.23 on 2026-01-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_simplify_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='listening_audio_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='听力音频时长(秒)'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='listening_audio_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='听力音频URL'),
        ),
    ]
