# Generated by Django 4.2.23 on 2026-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_questionset_listening_audio_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='listening_audio_duration',
            field=models.IntegerField(default=0, verbose_name='听力完整音频时长(秒)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='listening_audio_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='听力完整音频URL'),
        ),
    ]
