# Generated by Django 4.2.23 on 2026-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_alter_questionset_listening_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_type',
            field=models.CharField(choices=[('text', '文字选项'), ('image', '图片选项')], default='text', max_length=10, verbose_name='选项类型'),
        ),
    ]
