# Generated by Django 4.2.23 on 2026-01-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_question_option_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamComment',
        ),
    ]
